# Generated by Django 2.1 on 2019-08-15 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miappotro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEjemplar', models.IntegerField(max_length=11)),
                ('FechaCompra', models.DateField()),
                ('Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miappotro.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fechaprestamo', models.DateField()),
                ('NombreCliente', models.CharField(max_length=45)),
                ('TelefonoCliente', models.CharField(max_length=45)),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='Ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miappotro.Ejemplar'),
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='Prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miappotro.Prestamo'),
        ),
    ]
