# Generated by Django 2.1 on 2019-08-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappotro', '0002_auto_20190815_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='NumeroEjemplar',
            field=models.IntegerField(),
        ),
    ]
